name: CICD With Docker
# Trigger the workflow whenever code is pushed to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  # CI Job - Builds and pushes the Docker image to Docker Hub
  build:
    runs-on: ubuntu-latest # Uses the latest Ubuntu runner from GitHub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/authservice:latest .

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/authservice:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Free up disk space on self-hosted runner
        run: |
          docker system prune -af
          docker volume prune -f
          docker network prune -f
          df -h  # Show disk space after cleanup

      - name: Pull the latest Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/authservice:latest

      - name: Stop and remove old Docker container (if running)
        run: |
          sudo docker stop authservice-container || true
          sudo docker rm -f authservice-container || true

      - name: Run new Docker container
        run: sudo docker run -d --restart unless-stopped -p 8080:8080 --name authservice-container ${{ secrets.DOCKER_USERNAME }}/authservice:latest
